export const REQUEST_ENTITY = 'FETCH_ENTITY'
export const REQUEST_ENTITY_SUCCESS = 'FETCH_ENTITY_SUCCESS'
export const REQUEST_ENTITY_ERROR = 'FETCH_ENTITY_ERROR'
export const REQUEST_SIMILAR_SUCCESS = 'FETCH_SIMILAR_SUCCESS'
